assert(vim.fn.has("nvim-0.12") == 1, "Neovim 0.12+ is required")
assert(vim.o.tabstop == 4 and vim.o.shiftwidth == 4, "four-space indentation is not active")
assert(vim.g.colors_name == "omarchy", "Omarchy colorscheme did not load")
assert(vim.fn.exists(":Theme") == 2, ":Theme command is missing")
assert(vim.fn.exists(":ConfigDocs") == 2, ":ConfigDocs command is missing")
assert(vim.fn.maparg("<leader>ff", "n") ~= "", "file picker mapping is missing")
assert(vim.fn.maparg("<leader>fw", "n") ~= "", "live grep mapping is missing")
assert(vim.fn.maparg("<C-h>", "n") ~= "", "pane navigation mapping is missing")
assert(#vim.pack.get(nil, { info = false }) == 8, "unexpected plugin count")

print("nvim2: all checks passed")
vim.cmd.qall()
